<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-HS5RCHRC" ignored="0" name="Default test" tests="8" failures="1" timestamp="13 Feb 2020 04:46:49 GMT" time="140.97" errors="0">
  <testcase name="navigateToCategoryBagsAccessories" time="7.213" classname="com.Arcadia.Testcases.HomePageTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.Arcadia.Utility.BaseClass.checkTitle(BaseClass.java:122)
	at com.Arcadia.Pages.BagsAccessoriesPage.checkBagsAccessoriesTitle(BagsAccessoriesPage.java:17)
	at com.Arcadia.Testcases.HomePageTest.navigateToCategoryBagsAccessories(HomePageTest.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- navigateToCategoryBagsAccessories -->
  <testcase name="navigateToCategoryBrands" time="7.373" classname="com.Arcadia.Testcases.HomePageTest"/>
  <testcase name="navigateToCategoryClothing" time="7.307" classname="com.Arcadia.Testcases.HomePageTest"/>
  <testcase name="navigateToCategoryDresses" time="7.443" classname="com.Arcadia.Testcases.HomePageTest"/>
  <testcase name="navigateToCategoryJeans" time="7.435" classname="com.Arcadia.Testcases.HomePageTest"/>
  <testcase name="navigateToCategorySale" time="7.404" classname="com.Arcadia.Testcases.HomePageTest"/>
  <testcase name="navigateToCategoryShoes" time="7.242" classname="com.Arcadia.Testcases.HomePageTest"/>
  <testcase name="navigateToNewIn" time="7.388" classname="com.Arcadia.Testcases.HomePageTest"/>
</testsuite> <!-- Default test -->
